# Generated by Django 2.2.3 on 2019-07-26 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('type', models.TextField(choices=[('Cn', '中文'), ('En', '英文')], default='Cn', max_length=2, verbose_name='类型')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('testID', models.IntegerField(primary_key=True, serialize=False, verbose_name='测试编号')),
                ('school', models.CharField(max_length=4, verbose_name='学校')),
                ('classInfo', models.CharField(max_length=5, verbose_name='班级')),
                ('articleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typingPage.article')),
            ],
            options={
                'verbose_name': '测试',
                'verbose_name_plural': '测试',
            },
        ),
        migrations.CreateModel(
            name='typingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typing_date', models.DateTimeField(verbose_name='测试时间')),
                ('right', models.IntegerField(default=0, verbose_name='正确数')),
                ('error', models.IntegerField(default=0, verbose_name='错误数')),
                ('rate', models.IntegerField(default=0, verbose_name='正确率')),
                ('stuID', models.CharField(max_length=200, verbose_name='学号/姓名')),
            ],
            options={
                'verbose_name': '打字测试数据',
                'verbose_name_plural': '打字测试数据',
            },
        ),
        migrations.CreateModel(
            name='testRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuName', models.CharField(max_length=4, verbose_name='姓名')),
                ('speed', models.IntegerField(default=0, verbose_name='速度')),
                ('completionRate', models.IntegerField(default=0, verbose_name='完成率')),
                ('correctRate', models.IntegerField(default=0, verbose_name='正确率')),
                ('testID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typingPage.test')),
            ],
            options={
                'verbose_name': '测试结果',
                'verbose_name_plural': '测试结果',
            },
        ),
    ]
