# Generated by Django 2.2.3 on 2019-07-29 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typingPage', '0004_test_testtotaltime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('Cn', '中文'), ('En', '英文')], default='Cn', max_length=2, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='test',
            name='articleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typingPage.article', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='test',
            name='testTotalTime',
            field=models.IntegerField(default=20, verbose_name='测试时间（分）'),
        ),
    ]
