# Generated by Django 2.2.3 on 2019-07-29 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typingPage', '0005_auto_20190729_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='completionRate',
        ),
    ]
