# Generated by Django 2.2.3 on 2019-07-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typingPage', '0006_remove_testresult_completionrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='typingInfo',
        ),
        migrations.AddField(
            model_name='test',
            name='entryCode',
            field=models.CharField(default='123', max_length=20, verbose_name='测试码'),
        ),
    ]
