# Generated by Django 2.2.5 on 2019-11-17 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typingPage', '0007_auto_20190731_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='标题'),
        ),
        migrations.CreateModel(
            name='practiceResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuName', models.CharField(max_length=4, verbose_name='姓名')),
                ('speed', models.IntegerField(default=0, verbose_name='速度')),
                ('correctRate', models.IntegerField(default=0, verbose_name='正确率')),
                ('articleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_rank', to='typingPage.article')),
            ],
            options={
                'verbose_name': '练习结果',
                'verbose_name_plural': '练习结果',
            },
        ),
    ]
