# Generated by Django 2.2.5 on 2019-11-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typingPage', '0009_auto_20191117_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='isVisible',
            field=models.BooleanField(default=True, verbose_name='是否可见'),
        ),
    ]
