# Generated by Django 2.2.5 on 2019-11-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typingPage', '0010_article_isvisible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='correctRate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4, verbose_name='正确率'),
        ),
    ]
