# Generated by Django 2.2.5 on 2020-11-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typingPage', '0012_testresult_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceresult',
            name='score',
            field=models.IntegerField(default=0, verbose_name='得分'),
        ),
    ]
