# Generated by Django 2.2.5 on 2021-04-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typingPage', '0015_auto_20201109_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='isVisible',
            field=models.BooleanField(default=False, verbose_name='是否可见'),
        ),
        migrations.AlterField(
            model_name='practiceresult',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='得分'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='得分'),
        ),
    ]
