# Generated by Django 2.2.5 on 2021-04-22 01:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typingPage', '0017_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(default=datetime.date(2020, 12, 31)),
        ),
    ]
