# Generated by Django 2.2.5 on 2021-04-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typingPage', '0018_auto_20210422_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(default='2020-12-31'),
        ),
    ]
