# Generated by Django 2.2.5 on 2021-04-22 01:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('typingPage', '0021_auto_20210422_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
