# Generated by Django 2.2.5 on 2021-04-22 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('typingPage', '0024_auto_20210422_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='testDate',
        ),
    ]
