# Generated by Django 3.2.6 on 2021-08-20 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typingPage', '0028_auto_20210815_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='编号')),
                ('school', models.CharField(choices=[('沙城一小', '沙城一小')], default='沙城一小', max_length=10, verbose_name='学校')),
                ('classNum', models.CharField(max_length=5, verbose_name='班级')),
            ],
            options={
                'verbose_name': '01 - 学校班级',
                'verbose_name_plural': '01 - 学校班级',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '03 - 文章', 'verbose_name_plural': '03 - 文章'},
        ),
        migrations.AlterModelOptions(
            name='practiceresult',
            options={'verbose_name': '04 - 练习结果', 'verbose_name_plural': '04 - 练习结果'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': '05 - 测试', 'verbose_name_plural': '05 - 测试'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': '06 - 测试结果', 'verbose_name_plural': '06 - 测试结果'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '02 - 用户', 'verbose_name_plural': '02 - 用户'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='school',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stuClass',
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='任务编号')),
                ('book', models.CharField(choices=[('六上', '六上'), ('六下', '六下'), ('五上', '五上')], default='六上', max_length=2, verbose_name='册')),
                ('unit', models.CharField(choices=[('1', '第一单元'), ('2', '第二单元'), ('3', '第三单元')], default='1', max_length=4, verbose_name='单元')),
                ('lesson', models.CharField(default='第1课', max_length=30, verbose_name='课')),
                ('SchoolClass', models.ManyToManyField(blank=True, to='typingPage.SchoolClass')),
            ],
            options={
                'verbose_name': '06 - 任务',
                'verbose_name_plural': '06 - 任务',
            },
        ),
        migrations.CreateModel(
            name='classwork',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='作业编号')),
                ('speed', models.IntegerField(default=0, verbose_name='速度')),
                ('UID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classwork_uid', to='typingPage.user', verbose_name='学生')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classwork_task', to='typingPage.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '05 - 课堂作业',
                'verbose_name_plural': '05 - 课堂作业',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='SchoolClass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schoolclass_user', to='typingPage.schoolclass', verbose_name='学校班级'),
        ),
    ]
