# Generated by Django 3.2.6 on 2021-08-21 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typingPage', '0029_auto_20210820_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practiceresult',
            name='UID',
        ),
        migrations.AddField(
            model_name='practiceresult',
            name='school',
            field=models.CharField(default='', max_length=10, verbose_name='学校'),
        ),
        migrations.AddField(
            model_name='practiceresult',
            name='stuClass',
            field=models.CharField(default='', max_length=6, verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='practiceresult',
            name='stuName',
            field=models.CharField(default='', max_length=5, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='test',
            name='testTotalTime',
            field=models.IntegerField(default=10, verbose_name='测试时间（分）'),
        ),
    ]
