# Generated by Django 3.2.6 on 2021-08-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typingPage', '0030_auto_20210821_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classwork',
            options={'verbose_name': '08 - 课堂作业', 'verbose_name_plural': '08 - 课堂作业'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '07 - 任务', 'verbose_name_plural': '07 - 任务'},
        ),
        migrations.RemoveField(
            model_name='classwork',
            name='speed',
        ),
        migrations.AddField(
            model_name='classwork',
            name='filePath',
            field=models.CharField(default='', max_length=200, verbose_name='保存路径'),
        ),
        migrations.AddField(
            model_name='task',
            name='rootDir',
            field=models.CharField(default='C:\\task', max_length=200, verbose_name='存储根目录'),
        ),
        migrations.AlterField(
            model_name='task',
            name='book',
            field=models.CharField(choices=[('六上', '六上'), ('六下', '六下'), ('五上', '五上'), ('五下', '五下'), ('四上', '四上'), ('四下', '四下'), ('三上', '三上'), ('三下', '三下')], default='六上', max_length=2, verbose_name='册'),
        ),
    ]
