# Generated by Django 3.2.9 on 2025-01-08 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('typingPage', '0032_auto_20210821_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='isUploaded',
        ),
        migrations.CreateModel(
            name='classCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='班级码编号')),
                ('code', models.CharField(default='', max_length=10, verbose_name='班级码')),
                ('SchoolClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schoolclass_code', to='typingPage.schoolclass', verbose_name='学校班级')),
            ],
            options={
                'verbose_name': '09 - 班级码',
                'verbose_name_plural': '09 - 班级码',
            },
        ),
    ]
